apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-web-app
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://10.89.0.3:6443
    namespace: prod-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
