apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: web-app-dev
  labels:
    app: web-app-dev
spec:
  deletionPolicy: Delete
  forProvider:
    description: Allow airflow access to sqs
    document: >
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "sqs:ChangeMessageVisibility",
                      "sqs:DeleteMessage",
                      "sqs:GetQueueAttributes",
                      "sqs:GetQueueUrl",
                      "sqs:ReceiveMessage",
                      "sqs:SendMessage"
                  ],
                  "Resource": "arn:aws:sqs:us-east-1:000000000000:web-app-dev-queue"
              }
          ]
        }
    name: web-app-dev
  providerConfigRef:
    name: localstack