apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sqs-with-dlq
spec:
  compositeTypeRef:
    apiVersion: messaging.example.io/v1alpha1
    kind: XSQSQueue
  
  mode: Pipeline
  pipeline:
  - step: dlq
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: dlq
        base:
          apiVersion: sqs.aws.crossplane.io/v1beta1
          kind: Queue
          spec:
            forProvider:
              region: us-east-1
              messageRetentionPeriod: 1209600
            providerConfigRef:
              name: localstack
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.queueName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-dlq"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.url
          toFieldPath: status.dlqUrl
          policy:
            fromFieldPath: Optional

      - name: main-queue
        base:
          apiVersion: sqs.aws.crossplane.io/v1beta1
          kind: Queue
          spec:
            forProvider:
              region: us-east-1
              visibilityTimeout: 30
              messageRetentionPeriod: 345600
            providerConfigRef:
              name: localstack
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.queueName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.visibilityTimeout
          toFieldPath: spec.forProvider.visibilityTimeout
        - type: FromCompositeFieldPath
          fromFieldPath: spec.messageRetentionPeriod
          toFieldPath: spec.forProvider.messageRetentionPeriod
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.url
          toFieldPath: status.queueUrl
          policy:
            fromFieldPath: Optional

      - name: iam-role
        base:
          apiVersion: iam.aws.crossplane.io/v1beta1
          kind: Role
          spec:
            forProvider:
              region: us-east-1
              assumeRolePolicyDocument: |
                {
                  "Version": "2012-10-17",
                  "Statement": [{
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "eks.amazonaws.com",
                      "Federated": "arn:aws:iam::000000000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity"
                  }]
                }
            providerConfigRef:
              name: localstack
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.iamRoleName
          toFieldPath: metadata.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.roleArn
          policy:
            fromFieldPath: Optional

      - name: iam-policy
        base:
          apiVersion: iam.aws.crossplane.io/v1beta1
          kind: RolePolicy
          spec:
            forProvider:
              region: us-east-1
              roleNameRef:
                name: placeholder
            providerConfigRef:
              name: localstack
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.iamRoleName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-policy"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.iamRoleName
          toFieldPath: spec.forProvider.roleNameRef.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.queueName
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [{
                    "Effect": "Allow",
                    "Action": [
                      "sqs:SendMessage",
                      "sqs:ReceiveMessage",
                      "sqs:DeleteMessage",
                      "sqs:GetQueueAttributes"
                    ],
                    "Resource": "arn:aws:sqs:us-east-1:000000000000:%s"
                  }]
                }
          toFieldPath: spec.forProvider.document
